package view;

import aksesdata.AksesDataPembayaran;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.ModelPembayaran;

public class LihatPembayaran extends javax.swing.JFrame {

    private final int idKasir;
    private final AksesDataPembayaran aksesDataPembayaran;

    /**
     * Creates new form LihatPembayaran
     */
    public LihatPembayaran(int idKasir) throws SQLException {
        initComponents();
        this.idKasir = idKasir;
        this.aksesDataPembayaran = new AksesDataPembayaran();
        this.tabelPembayaran.setModel(this.viewTabel());
        this.setVisible(true);
    }

    public DefaultTableModel viewTabel() throws SQLException {
        DefaultTableModel dtmPembayaran = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        dtmPembayaran.addColumn("ID Pembayaran");
        dtmPembayaran.addColumn("ID Kasir");
        dtmPembayaran.addColumn("ID Member");
        dtmPembayaran.addColumn("Tanggal Pembayaran");
        dtmPembayaran.addColumn("Harga Tiket");
        dtmPembayaran.addColumn("Banyak Tiket");
        dtmPembayaran.addColumn("Total");

        ArrayList<ModelPembayaran> daftarDataPembayaran = this.aksesDataPembayaran.read();
        for (int i = 0; i < daftarDataPembayaran.size(); i++) {
            Object[] temp = new Object[7];
            temp[0] = daftarDataPembayaran.get(i).getIdPembayaran();
            temp[1] = daftarDataPembayaran.get(i).getModelKasir().getIdKasir();
            temp[2] = daftarDataPembayaran.get(i).getModelMember().getIdMember();
            String tanggalPembayaranTerformat = new SimpleDateFormat("dd/MM/yyyy").format(
                    daftarDataPembayaran.get(i).getTanggalPembayaran());
            temp[3] = tanggalPembayaranTerformat;
            temp[4] = daftarDataPembayaran.get(i).getHargaTiket();
            temp[5] = daftarDataPembayaran.get(i).getBanyakTiket();
            temp[6] = daftarDataPembayaran.get(i).getTotal();

            dtmPembayaran.addRow(temp);
        }

        return dtmPembayaran;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPembayaran = new javax.swing.JTable();
        buttonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("                          Hasil Pembayaran");

        tabelPembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelPembayaran);

        buttonBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonBack.setText("Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBack, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        Menu menu = new Menu(this.idKasir);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPembayaran;
    // End of variables declaration//GEN-END:variables
}
