/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alexander Pratama
 */
public class Menu extends javax.swing.JFrame {
    
    private final int idKasir;

    /**
     * Creates new form Menu
     */
    public Menu(int idKasir) {
        initComponents();
        this.idKasir = idKasir;
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonnewmem = new javax.swing.JButton();
        buttonnewpemb = new javax.swing.JButton();
        labeljudulmenu = new javax.swing.JLabel();
        buttonlogout = new javax.swing.JButton();
        buttonLihatPembayaran = new javax.swing.JButton();
        buttoneditmember = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonnewmem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonnewmem.setText("Registrasi Member");
        buttonnewmem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonnewmemActionPerformed(evt);
            }
        });

        buttonnewpemb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonnewpemb.setText("Transaksi Pembayaran");
        buttonnewpemb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonnewpembActionPerformed(evt);
            }
        });

        labeljudulmenu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labeljudulmenu.setText("Menu Kasir");

        buttonlogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonlogout.setText("Log Out");
        buttonlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonlogoutActionPerformed(evt);
            }
        });

        buttonLihatPembayaran.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonLihatPembayaran.setText("Lihat Pembayaran");
        buttonLihatPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLihatPembayaranActionPerformed(evt);
            }
        });

        buttoneditmember.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttoneditmember.setText("Edit Member");
        buttoneditmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoneditmemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 92, Short.MAX_VALUE)
                .addComponent(labeljudulmenu)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(buttonlogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonnewpemb, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(buttonnewmem, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addComponent(buttoneditmember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(buttonLihatPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeljudulmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(buttonnewmem, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttoneditmember, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonnewpemb, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonLihatPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(buttonlogout)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonnewmemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonnewmemActionPerformed
        try {
            NewMember newmem = new NewMember(this.idKasir);
            newmem.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonnewmemActionPerformed

    private void buttonnewpembActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonnewpembActionPerformed
        try {
            Pembayaran pemb = new Pembayaran(this.idKasir);
            pemb.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonnewpembActionPerformed

    private void buttonlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonlogoutActionPerformed
        Login log = new Login();
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonlogoutActionPerformed

    private void buttonLihatPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLihatPembayaranActionPerformed
        try {
            LihatPembayaran lihatPembayaran = new LihatPembayaran(this.idKasir);
            lihatPembayaran.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonLihatPembayaranActionPerformed

    private void buttoneditmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoneditmemberActionPerformed
        try {
            UpdateDeleteMember updel = new UpdateDeleteMember(this.idKasir);
            updel.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttoneditmemberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLihatPembayaran;
    private javax.swing.JButton buttoneditmember;
    private javax.swing.JButton buttonlogout;
    private javax.swing.JButton buttonnewmem;
    private javax.swing.JButton buttonnewpemb;
    private javax.swing.JLabel labeljudulmenu;
    // End of variables declaration//GEN-END:variables
}
