/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import aksesdata.AksesDataMember;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.table.DefaultTableModel;
import model.ModelMember;

/**
 *
 * @author Alexander Pratama
 */
public class UpdateDeleteMember extends javax.swing.JFrame {
    private final int idKasir;
    private final AksesDataMember aksesDataMember;

    
    public UpdateDeleteMember(int idKasir) throws SQLException {
        initComponents();
        this.idKasir = idKasir;
        this.aksesDataMember = new AksesDataMember();
        this.setVisible(true);
    }
    
    private boolean cekTextBagianUpdateKosong() {
        boolean textBagianUpdateKosong = false;
        if (this.textIdMemberAkanDiupdate.getText().isEmpty()
                || this.textNamaMemberAkanDiupdate.getText().isEmpty()
                || this.textNoTeleponAkanDiupdate.getText().isEmpty()
                || this.textNamaMemberUpdate.getText().isEmpty()
                || this.textNoTeleponUpdate.getText().isEmpty()){
            textBagianUpdateKosong = true;}
        return textBagianUpdateKosong;
    }
    
    private boolean cekTextBagianHapusKosong() {
        return this.textIdMemberAkanDihapus.getText().isEmpty()
                ||this.textNamaMemberAkanDihapus.getText().isEmpty();
    }
    
    private boolean validasiInputanUpdateError() {
        String pesanErrorIdMember = "";

        boolean errorInputIdMember;
        try {
            int idMember = Integer.parseInt(this.textIdMemberAkanDiupdate.getText());
            errorInputIdMember = false;
        } catch (NumberFormatException error) {
            errorInputIdMember = true;
            pesanErrorIdMember = String.valueOf(error);
        }

        if (errorInputIdMember) {
            JOptionPane.showMessageDialog(null, "ID Member hanya menerima masukan berupa angka.\n"
                    + pesanErrorIdMember, "Peringatan", WARNING_MESSAGE);
        }
        return errorInputIdMember;
    }
    
    private boolean validasiInputanHapusError() {
        String pesanErrorIdMember = "";

        boolean errorInputIdMember;
        try {
            int idMember = Integer.parseInt(this.textIdMemberAkanDihapus.getText());
            errorInputIdMember = false;
        } catch (NumberFormatException error) {
            errorInputIdMember = true;
            pesanErrorIdMember = String.valueOf(error);
        }

        if (errorInputIdMember) {
            JOptionPane.showMessageDialog(null, "ID Member hanya menerima masukan berupa angka.\n"
                    + pesanErrorIdMember, "Peringatan", WARNING_MESSAGE);
        }
        return errorInputIdMember;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textIdMemberAkanDiupdate = new javax.swing.JTextField();
        buttonCariMemberAkanDiupdate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textNamaMemberAkanDiupdate = new javax.swing.JTextField();
        textNoTeleponAkanDiupdate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textNamaMemberUpdate = new javax.swing.JTextField();
        textNoTeleponUpdate = new javax.swing.JTextField();
        buttonUpdateDataMember = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        textIdMemberAkanDihapus = new javax.swing.JTextField();
        buttonCariMemberAkanDihapus = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        textNamaMemberAkanDihapus = new javax.swing.JTextField();
        textNoTeleponAkanDihapus = new javax.swing.JTextField();
        buttonHapusMember = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Member");

        jLabel2.setText("ID Member yang akan di Update");

        buttonCariMemberAkanDiupdate.setText("Cari Member");
        buttonCariMemberAkanDiupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariMemberAkanDiupdateActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Data Member yang akan di Update");

        jLabel4.setText("Nama Member");

        jLabel5.setText("No Telp");

        textNoTeleponAkanDiupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNoTeleponAkanDiupdateActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Data di Update Menjadi");

        jLabel7.setText("Nama Member");

        jLabel8.setText("No Telp");

        buttonUpdateDataMember.setText("Update");
        buttonUpdateDataMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateDataMemberActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Delete Member");

        jLabel10.setText("ID Member yang akan di Delete");

        buttonCariMemberAkanDihapus.setText("Cari Member");
        buttonCariMemberAkanDihapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariMemberAkanDihapusActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Data Member yang akan di Delete");

        jLabel12.setText("Nama Member");

        jLabel13.setText("No Telp");

        buttonHapusMember.setText("Delete");
        buttonHapusMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusMemberActionPerformed(evt);
            }
        });

        buttonBack.setText("Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonUpdateDataMember, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(textIdMemberAkanDiupdate))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonCariMemberAkanDiupdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textNamaMemberAkanDiupdate)
                                    .addComponent(textNoTeleponAkanDiupdate)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textNamaMemberUpdate)
                                    .addComponent(textNoTeleponUpdate)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(textIdMemberAkanDihapus))
                            .addComponent(buttonCariMemberAkanDihapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textNamaMemberAkanDihapus)
                                    .addComponent(textNoTeleponAkanDihapus)))
                            .addComponent(buttonHapusMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textIdMemberAkanDiupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(textIdMemberAkanDihapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCariMemberAkanDiupdate)
                    .addComponent(buttonCariMemberAkanDihapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textNamaMemberAkanDiupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(textNamaMemberAkanDihapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textNoTeleponAkanDiupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(textNoTeleponAkanDihapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(buttonHapusMember))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(textNamaMemberUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(textNoTeleponUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonUpdateDataMember)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonBack, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNoTeleponAkanDiupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNoTeleponAkanDiupdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNoTeleponAkanDiupdateActionPerformed

    private void buttonCariMemberAkanDiupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariMemberAkanDiupdateActionPerformed
         boolean ketemu = false;
        if (this.textIdMemberAkanDiupdate.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Silahkan isi ID pegawai terlebih dahulu", "Peringatan",
                    WARNING_MESSAGE);
        } else {
             try {
                 if (!this.aksesDataMember.cekDataMemberMasihKosong()) {
                     int idMember = Integer.parseInt(this.textIdMemberAkanDiupdate.getText());
                     ModelMember modelMember = this.aksesDataMember.cariDataMember(idMember);
                     if (modelMember != null) {
                         this.textNamaMemberAkanDiupdate.setText(modelMember.getNamaMember());
                         this.textNoTeleponAkanDiupdate.setText(String.valueOf(modelMember.getNoTelpMember()));
                         this.textNamaMemberAkanDiupdate.setEnabled(true);
                         this.textNoTeleponAkanDiupdate.setEnabled(true);
                         ketemu = true;
                     }
                 } else {
                     JOptionPane.showMessageDialog(null, "Data member masih kosong",
                             "Peringatan", WARNING_MESSAGE);
                 }
                 if (!ketemu && !this.aksesDataMember.cekDataMemberMasihKosong()) {
                     JOptionPane.showMessageDialog(null, "Member yang dicari tidak ditemukan, "
                             + "silahkan masukkan ID yang benar", "Peringatan", WARNING_MESSAGE);
                 }} catch (SQLException ex) {
                 Logger.getLogger(UpdateDeleteMember.class.getName()).log(Level.SEVERE, null, ex);
             }
        }                     
    }//GEN-LAST:event_buttonCariMemberAkanDiupdateActionPerformed

    private void buttonUpdateDataMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateDataMemberActionPerformed
        if (this.cekTextBagianUpdateKosong()) {
            JOptionPane.showMessageDialog(null, "Isi semua kolom isian terlebih dahulu", "Gagal Update",
                    WARNING_MESSAGE);
        } else {
            if (!this.validasiInputanUpdateError()) {
                int konfirmasi = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin untuk "
                        + "mengupdate data member tersebut ?", "Konfirmasi", OK_CANCEL_OPTION,
                        QUESTION_MESSAGE);
                if (konfirmasi == 0) {
                    int idMember = Integer.parseInt(this.textIdMemberAkanDiupdate.getText());
                    String namaMember = this.textNamaMemberUpdate.getText();
                    int noTelpMember= Integer.parseInt(this.textNoTeleponUpdate.getText());
                    this.aksesDataMember.update(idMember, namaMember, noTelpMember);
                    JOptionPane.showMessageDialog(null, "Data pegawai tersebut berhasil diupdate");
                }
            }
        }
    }//GEN-LAST:event_buttonUpdateDataMemberActionPerformed

    private void buttonCariMemberAkanDihapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariMemberAkanDihapusActionPerformed
        boolean ketemu = false;
        if (this.textIdMemberAkanDihapus.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Silahkan isi ID pegawai terlebih dahulu", "Peringatan",
                    WARNING_MESSAGE);
        } else {
            try {
                if (!this.aksesDataMember.cekDataMemberMasihKosong()) {
                    int idMember = Integer.parseInt(this.textIdMemberAkanDihapus.getText());
                    ModelMember modelMember = this.aksesDataMember.cariDataMember(idMember);
                    if (modelMember != null) {
                        this.textNamaMemberAkanDihapus.setText(modelMember.getNamaMember());
                        this.textNoTeleponAkanDihapus.setText(String.valueOf(modelMember.getNoTelpMember()));
                        this.textNamaMemberAkanDihapus.setEnabled(true);
                        this.textNoTeleponAkanDihapus.setEnabled(true);
                        ketemu = true;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Data pegawai masih kosong",
                            "Peringatan", WARNING_MESSAGE);
                }
                if (!ketemu && !this.aksesDataMember.cekDataMemberMasihKosong()) {
                    JOptionPane.showMessageDialog(null, "Member yang dicari tidak ditemukan, "
                            + "silahkan masukkan ID yang benar", "Peringatan", WARNING_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(UpdateDeleteMember.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonCariMemberAkanDihapusActionPerformed

    private void buttonHapusMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusMemberActionPerformed
        if (this.cekTextBagianHapusKosong()) {
            JOptionPane.showMessageDialog(null, "Isi semua kolom isian terlebih dahulu", "Gagal Hapus",
                    WARNING_MESSAGE);
        } else {
            if (!this.validasiInputanHapusError()) {
                int konfirmasi = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin untuk menghapus "
                        + "data member tersebut ?", "Konfirmasi",
                        OK_CANCEL_OPTION, QUESTION_MESSAGE);
                if (konfirmasi == 0) {
                    int idMember = Integer.parseInt(this.textIdMemberAkanDihapus.getText());
                    this.aksesDataMember.delete(idMember);
                    JOptionPane.showMessageDialog(null, "Data member tersebut berhasil dihapus");
                }
            }
        }
    }//GEN-LAST:event_buttonHapusMemberActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        Menu menu = new Menu(this.idKasir);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonBackActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonCariMemberAkanDihapus;
    private javax.swing.JButton buttonCariMemberAkanDiupdate;
    private javax.swing.JButton buttonHapusMember;
    private javax.swing.JButton buttonUpdateDataMember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textIdMemberAkanDihapus;
    private javax.swing.JTextField textIdMemberAkanDiupdate;
    private javax.swing.JTextField textNamaMemberAkanDihapus;
    private javax.swing.JTextField textNamaMemberAkanDiupdate;
    private javax.swing.JTextField textNamaMemberUpdate;
    private javax.swing.JTextField textNoTeleponAkanDihapus;
    private javax.swing.JTextField textNoTeleponAkanDiupdate;
    private javax.swing.JTextField textNoTeleponUpdate;
    // End of variables declaration//GEN-END:variables
}
